<<<<<<< HEAD
# MINIMAL local values for kind
replicaCount: 1

image:
  repository: platform-in-a-box   # local image name
=======
replicaCount: 1

image:
  repository: platform-in-a-box   # local image you built
>>>>>>> origin/main
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
<<<<<<< HEAD
  enabled: false   # keep off until we’re green
=======
  enabled: true
  className: "nginx"
  hosts:
    - host: pib.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
>>>>>>> origin/main

resources:
  requests: { cpu: 50m, memory: 128Mi }
  limits:   { cpu: 300m, memory: 256Mi }
