# MINIMAL local values for kind
replicaCount: 1

image:
  repository: platform-in-a-box   # local image name
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false   # keep off until we’re green

resources:
  requests: { cpu: 50m, memory: 128Mi }
  limits:   { cpu: 300m, memory: 256Mi }
