name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build API
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/platform-api:${{ github.ref_name }} apps/api
          docker push ghcr.io/${{ github.repository_owner }}/platform-api:${{ github.ref_name }}
      - name: Build Web
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/platform-web:${{ github.ref_name }} apps/web
          docker push ghcr.io/${{ github.repository_owner }}/platform-web:${{ github.ref_name }}
