name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Build & Push image
        env:
          IMAGE: ghcr.io/${{ github.repository }}/app:${{ github.ref_name }}
        run: |
          docker build -t $IMAGE .
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $IMAGE
