name: CI
on:
  push:
    branches: [ main, polish/** ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_BASE: ghcr.io/${{ github.repository }}/app

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build -t $IMAGE_BASE:sha-${GITHUB_SHA} .

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image (sha tag)
        run: docker push $IMAGE_BASE:sha-${GITHUB_SHA}

      # >>> THIS IS STEP 3: tag with the PR number and push <<<
      - name: Tag & push PR-number image
        if: github.event_name == 'pull_request'
        run: |
          docker tag $IMAGE_BASE:sha-${GITHUB_SHA} $IMAGE_BASE:pr-${{ github.event.pull_request.number }}
          docker push $IMAGE_BASE:pr-${{ github.event.pull_request.number }}
