name: CI
on:
  push:
    branches: [ main, polish/** ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Build container
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/app:pr-${{ github.run_number }}
          docker build -t $IMAGE .

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/app:pr-${{ github.run_number }}
          docker push $IMAGE
