name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Kind cluster (ephemeral)
        uses: helm/kind-action@v1
        with:
          cluster_name: pib-ci

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Deploy preview (placeholder)
        env:
          NAMESPACE: pr-${{ github.event.pull_request.number }}
        run: |
          kubectl create ns $NAMESPACE || true
          kubectl get ns

      - name: Comment namespace
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          message: |
            Preview deployed to namespace **pr-${{ github.event.pull_request.number }}** on a kind cluster (CI demo).
